# the core of setting up fluent-bit

[SERVICE]
    Flush         10       # send buffered events to output every 10 second
    Daemon        Off     # runs in foreground (good for dev/docker)
    Log_Level     info    # fluent bit's own internal log verbosity
    Parsers_File  parsers.conf  # load your parser definitions from this file

[INPUT]
    Name              tail          # use the tail plugin (like `tail -f`)
    Tag               shazam.logs   # internal routing label for this stream
    Path              ../logs/shazam.log  # file to watch (see zap.go lumberjack setup) [use absolute paths in production]
    Parser            shazam_parser          # apply the json parser defined in parsers.conf
    DB                ./tail-state.db    # checkpoint file — explained below
    Read_from_Head    true          # on first start, read from beginning of file (could be end in some cases)
    Rotate_Wait       30            # seconds to wait after rotation before closing
    Refresh_Interval  5             # re-scan the file for new lines every 5s

# DB ./tail-state.db — this is important.
# Fluent Bit writes a small SQLite file here that tracks how far it has read in your log file (the byte offset / inode). So even if it crashes and restarts, it can start from where it crashed
# Fluent Bit creates the file on first run if it doesn't exist. You never manually create it. The directory must exist though 

# Rotate_Wait X — after lumberjack renames shazam.log → shazam-2026-04-03.log (old archived ones), Fluent Bit waits X seconds before it stops reading the old file. This is the safety buffer to make sure it catches any last lines written before the rename completed

# It does not mean logs are delayed by X seconds end-to-end. It means the maximum lag between your app writing a line and Fluent Bit picking it up is X seconds


# For now we only print what Fluent Bit read, so you can verify ingestion.
# where data goes 
[OUTPUT]
    Name   stdout
    Match  shazam.logs   # only process events with this tag

