# tells fluent-bit how our logs looks like
# that it contains a timestamp field named "time" in ISO8601 format, so it can parse it correctly.
# you can also have multiple parsers each consuming imputs with diff tags

[PARSER]
    Name        shazam_parser   # identifier for this parser, referenced in fluent-bit.conf INPUT section
    Format      json # could be regex, logfmt, ltsv. but zap outputs json
    Time_Key    time   # the field in our log that contains the timestamp. zap's default is "time", but you can configure it in zap's EncoderConfig
    Time_Format %Y-%m-%dT%H:%M:%S%z # ISO8601 format, matches zap's default. Adjust if you changed zap's time format.
